services:
  deluge:
    image: binhex/arch-deluge:latest
    container_name: deluge
    restart: unless-stopped
    ports:
      - "8112:8112/tcp"
      - "58846:58846/tcp"
      - "58946:58946/tcp"
      - "58946:58946/udp"
    environment:
      PUID: "99"
      PGID: "100"
      TZ: Europe/Oslo
      UMASK: "000"
      TCP_PORT_58846: "58846"
      TCP_PORT_58946: "58946"
      UDP_PORT_58946: "58946"
      TCP_PORT_8112: "8112"
    volumes:
      - "${DELUGE_CONFIG_PATH:?Set in Komodo}:/config"
      - /data:/data
      - deluge-shared:/shared

volumes:
  deluge-shared:
