version: "3.8"

services:
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: komodo-periphery-pc9
    restart: unless-stopped
    init: true
    network_mode: host
    volumes:
      - komodo_keys_pc9:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  komodo_keys_pc9:
    name: komodo_keys_pc9
