version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: "Europe/Oslo"
      WEBPASSWORD: "pro12345"
      DNS1: "1.1.1.1"
      DNS2: "8.8.8.8"
      DNSMASQ_LISTENING: "all"
      PUID: 99
      PGID: 100
    volumes:
      - "./config:/etc/pihole"
      - "./dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    networks:
      - komodo

networks:
  komodo:
    driver: bridge
