services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - homepage_config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo

volumes:
  homepage_config:
