version: "3.8"

services:
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:2
    container_name: komodo-core-1
    restart: unless-stopped
    init: true
    ports:
      - "9120:9120"
    environment:
      - KOMODO_DB_URI=mongodb://komodo-ferretdb:27017/komodo
      - KOMODO_INIT=true
    volumes:
      - komodo_keys:/config/keys
    depends_on:
      - komodo-ferretdb
    networks:
      - komodo_network

  komodo-ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    container_name: komodo-ferretdb-1
    restart: unless-stopped
    command: [ "-postgresql-url=postgres://username:password@komodo-postgres:5432/komodo" ]
    depends_on:
      - komodo-postgres
    networks:
      - komodo_network

  komodo-postgres:
    image: postgres:16-alpine
    container_name: komodo-postgres-1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=komodo
    volumes:
      - komodo_postgres_data:/var/lib/postgresql/data
    networks:
      - komodo_network

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: komodo-periphery-1
    restart: unless-stopped
    init: true
    volumes:
      - komodo_keys:/config/keys
    networks:
      - komodo_network

networks:
  komodo_network:
    name: komodo_default

volumes:
  komodo_keys:
    name: komodo_keys
  komodo_postgres_data:
    name: komodo_postgres_data
