services:
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: komodo-periphery
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - KOMODO_SECRET=MCowBQYDK2VuAyEAQzm6PFQP/YhNdIoHYLNz@P@or/&x/Xw
      - PERIPHERY_PORT=9121
      - PERIPHERY_SSL_ENABLED=false
      - TZ=Europe/Oslo
